<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BaseCharacterInfoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('base_character_info')->insert([
            ['name' => "uma",
            'typeEs' => "Pistolera, Core",
            'typeEn' => "Gunslinger, Core",
            'name_full' => "UMA SøRENSEN",
            'health' => 8,
            'Movement' => 6,
            'agro' => 5,
            'base_def' => "/4/",
            "head_id" => 0,
            "chest_id" => 0,
            "arm1_id" => 0,
            "arm2_id" => 0,
            "extra1_id" => 0,
            "extra2_id" => 0,
            'colorPrimeR' => 82,
            'colorPrimeG' => 155,
            'colorPrimeB' => 177,
            'colorSeconR' => 88,
            'colorSeconG' => 107,
            'colorSeconB' => 104,
            "automedKit_id" => 0],
            ['name' => "qiang",
            'typeEs' => "Armored, Core",
            'typeEn' => "Armored, Core",
            'name_full' => "QIANG GāO",
            'health' => 12,
            'Movement' => 5,
            'agro' => 8,
            'base_def' => "/4/",
            "head_id" => 0,
            "chest_id" => 0,
            "arm1_id" => 0,
            "arm2_id" => 0,
            "extra1_id" => 0,
            "extra2_id" => 0,
            'colorPrimeR' => 202,
            'colorPrimeG' => 191,
            'colorPrimeB' => 68,
            'colorSeconR' => 95,
            'colorSeconG' => 100,
            'colorSeconB' => 75,
            "automedKit_id" => 0],
            ['name' => "cadin",
            'typeEs' => "Luchador, Core",
            'typeEn' => "Fighter, Core",
            'name_full' => "CADIN \"FIRSTSTRIKE\"",
            'health' => 10,
            'Movement' => 6,
            'agro' => 4,
            'base_def' => "/4/",
            "head_id" => 0,
            "chest_id" => 0,
            "arm1_id" => 0,
            "arm2_id" => 0,
            "extra1_id" => 0,
            "extra2_id" => 0,
            'colorPrimeR' => 99,
            'colorPrimeG' => 146,
            'colorPrimeB' => 69,
            'colorSeconR' => 89,
            'colorSeconG' => 106,
            'colorSeconB' => 98,
            "automedKit_id" => 0],
            ['name' => "jazz",
            'typeEs' => "Hacker, Core",
            'typeEn' => "Hacker, Core",
            'name_full' => "JAZMÍN \"JAZZ\"",
            'health' => 8,
            'Movement' => 6,
            'agro' => 5,
            'base_def' => "/6/6/",
            "head_id" => 0,
            "chest_id" => 0,
            "arm1_id" => 0,
            "arm2_id" => 0,
            "extra1_id" => 0,
            "extra2_id" => 0,
            'colorPrimeR' => 195,
            'colorPrimeG' => 62,
            'colorPrimeB' => 56,
            'colorSeconR' => 110,
            'colorSeconG' => 98,
            'colorSeconB' => 97,
            "automedKit_id" => 0],
            ['name' => "rahman",
            'typeEs' => "Médico, Core",
            'typeEn' => "Doctor, Core",
            'name_full' => "RAHMAN ROUHANI",
            'health' => 9,
            'Movement' => 5,
            'agro' => 6,
            'base_def' => "/6/6/",
            "head_id" => 0,
            "chest_id" => 0,
            "arm1_id" => 0,
            "arm2_id" => 0,
            "extra1_id" => 0,
            "extra2_id" => 0,
            'colorPrimeR' => 190,
            'colorPrimeG' => 107,
            'colorPrimeB' => 63,
            'colorSeconR' => 134,
            'colorSeconG' => 120,
            'colorSeconB' => 95,
            "automedKit_id" => 0],
            ['name' => "trisha",
            'typeEs' => "Ingeniera, Core",
            'typeEn' => "Engineer, Core",
            'name_full' => "TRISHALA \"TRISHA\" N33",
            'health' => 8,
            'Movement' => 6,
            'agro' => 6,
            'base_def' => "/6/6/",
            "head_id" => 0,
            "chest_id" => 0,
            "arm1_id" => 0,
            "arm2_id" => 0,
            "extra1_id" => 0,
            "extra2_id" => 0,
            'colorPrimeR' => 103,
            'colorPrimeG' => 78,
            'colorPrimeB' => 167,
            'colorSeconR' => 72,
            'colorSeconG' => 48,
            'colorSeconB' => 132,
            "automedKit_id" => 0]
        ]);
    }
}
