<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SkilsAsociatedSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('skills_asociated')->insert([
            ['skill_id' => 1,
            'asociated_id' => 6,
            'type' => "characterSkill",
            'asociated_type' => "character",
            'group' => 1],
            ['skill_id' => 2,
            'asociated_id' => 6,
            'type' => "characterSkill",
            'asociated_type' => "character",
            'group' => 1],
            ['skill_id' => 3,
            'asociated_id' => 6,
            'type' => "characterSkill",
            'asociated_type' => "character",
            'group' => 2],
            ['skill_id' => 4,
            'asociated_id' => 6,
            'type' => "characterSkill",
            'asociated_type' => "character",
            'group' => 2],
            ['skill_id' => 5,
            'asociated_id' => 4,
            'type' => "characterSkill",
            'asociated_type' => "character",
            'group' => 3],
            ['skill_id' => 6,
            'asociated_id' => 4,
            'type' => "characterSkill",
            'asociated_type' => "character",
            'group' => 3],
            ['skill_id' => 7,
            'asociated_id' => 4,
            'type' => "characterSkill",
            'asociated_type' => "character",
            'group' => 4],
            ['skill_id' => 8,
            'asociated_id' => 4,
            'type' => "characterSkill",
            'asociated_type' => "character",
            'group' => 4],
            ['skill_id' => 9,
            'asociated_id' => 2,
            'type' => "characterSkill",
            'asociated_type' => "character",
            'group' => 5],
            ['skill_id' => 10,
            'asociated_id' => 2,
            'type' => "characterSkill",
            'asociated_type' => "character",
            'group' => 5],
            ['skill_id' => 11,
            'asociated_id' => 2,
            'type' => "characterSkill",
            'asociated_type' => "character",
            'group' => 6],
            ['skill_id' => 12,
            'asociated_id' => 2,
            'type' => "characterSkill",
            'asociated_type' => "character",
            'group' => 6],
            ['skill_id' => 13,
            'asociated_id' => 1,
            'type' => "characterSkill",
            'asociated_type' => "character",
            'group' => 7],
            ['skill_id' => 14,
            'asociated_id' => 1,
            'type' => "characterSkill",
            'asociated_type' => "character",
            'group' => 7],
            ['skill_id' => 15,
            'asociated_id' => 1,
            'type' => "characterSkill",
            'asociated_type' => "character",
            'group' => 8],
            ['skill_id' => 16,
            'asociated_id' => 1,
            'type' => "characterSkill",
            'asociated_type' => "character",
            'group' => 8],
            ['skill_id' => 17,
            'asociated_id' => 5,
            'type' => "characterSkill",
            'asociated_type' => "character",
            'group' => 9],
            ['skill_id' => 18,
            'asociated_id' => 5,
            'type' => "characterSkill",
            'asociated_type' => "character",
            'group' => 9],
            ['skill_id' => 19,
            'asociated_id' => 5,
            'type' => "characterSkill",
            'asociated_type' => "character",
            'group' => 10],
            ['skill_id' => 20,
            'asociated_id' => 5,
            'type' => "characterSkill",
            'asociated_type' => "character",
            'group' => 10],
            ['skill_id' => 21,
            'asociated_id' => 3,
            'type' => "characterSkill",
            'asociated_type' => "character",
            'group' => 11],
            ['skill_id' => 22,
            'asociated_id' => 3,
            'type' => "characterSkill",
            'asociated_type' => "character",
            'group' => 11],
            ['skill_id' => 23,
            'asociated_id' => 3,
            'type' => "characterSkill",
            'asociated_type' => "character",
            'group' => 12],
            ['skill_id' => 24,
            'asociated_id' => 3,
            'type' => "characterSkill",
            'asociated_type' => "character",
            'group' => 12],
            ['skill_id' => 25,
            'asociated_id' => 3,
            'type' => "characterSkill",
            'asociated_type' => "character",
            'group' => 13],
            ['skill_id' => 26,
            'asociated_id' => 3,
            'type' => "characterSkill",
            'asociated_type' => "character",
            'group' => 13],
        ]);
    }
}
